### ISSUE TITLE
0.10.0 - The file isn't a valid custom visual

### ISSUE THREAD

**Issue by yoalto** [iMicknl/powerbi-botframework-chat-transcripts#114]
When attempting to import latest release 0.10.0, ChatTranscripts2EB305C130CC44C4BBF62A1A900C5379.0.10.0.pbiviz,
getting this error:

![image](https://user-images.githubusercontent.com/95879848/145459909-6a2cdfd3-4acd-4350-b686-a9189f90035d.png)

Running Power BI Desktop Version: 2.99.782.0 64-bit (November, 2021)

**Comment by iMicknl** [comment]
Thanks for reporting @yoalto. Could you try https://github.com/iMicknl/powerbi-botframework-chat-transcripts/releases/tag/v0.9.1 in the mean-time?

I will investigate why 0.10.0 isn't working as it should be.

**Comment by iMicknl** [comment]
I can reproduce this issue and will have a look why it doesn't work anymore after the bump of `powerbi-visuals-tools` to 4.0.0.

For now, best is to use 0.9.1.

**Comment by iMicknl** [comment]
Fixed in v0.10.1! https://github.com/iMicknl/powerbi-botframework-chat-transcripts/releases/tag/v0.10.1
