### ISSUE TITLE
Feature Request - Date/Time Timestamps in Transcript Viewer

### ISSUE THREAD

**Issue by yoalto** [iMicknl/powerbi-botframework-chat-transcripts#116]
Currently, the transcript viewer shows "Yesterday" or "Today" as the timestamp for conversations in the last 2 days. I prefer to see the actual timestamp of each message sent/received, instead of simply "Yesterday" or "Today". A benefit of this would be seeing timestamps between each message (how long it takes for a user to respond).

**Comment by iMicknl** [comment]
@yoalto could you give https://github.com/iMicknl/powerbi-botframework-chat-transcripts/suites/4722832983/artifacts/129918605 a try? This is a packaged version based on #122.

**Comment by yoalto** [comment]
Yes, I can confirm the absolute time is displaying properly, and that the toggle is working properly to switch between the two options.
